embedding_size: 100
hidden_size: 128
model_path: models/
batch_size: 50
dropout: 0.5
epoch: 3
tags:
  - Medicinal_Name
  - Medicinal_Other_Name
  - Medicinal_Function
  - Medicinal_Taste
  - Medicinal_Use_Num
